### ISSUE TITLE
Setup Monitoring, and config docker

### ISSUE THREAD

**Issue by aswesty** [ebrvc/DevOps-GroupC#89]

**Comment by MartinLupa** [comment]
Additions:
- .NET Prometheus and monitoring packages.
- prometheus.yml file to scrap the http://localhost:5000/metrics endpoint in our app.
- root docker-compose.yml file to work as development.

> :warning: **Docker files**: We now have 3 docker-compose files (production -inside remote_files-, preproduction -inside preproduction_remote_files-, and at the root -development-).
Do we need this setup or is it possible to have only one at the root level? There are no differences between production and preproduction docker-compose files. 
If we keep these separation, we will also need to duplicate code to setup Prometheus and Grafana in production and preproduction.

**Comment by MartinLupa** [comment]
```/metrics``` endpoint working correctly on preproduction dropley on Digital Ocean (159.223.249.229:5000/metrics)

**Comment by MartinLupa** [comment]
TODO:
